# NOTE: Editing this file (provided it's in ~/.config) will
# automatically restart picom.  No need to restart it.

# Perform all rendering operations with OpenGL.
backend = "glx";

# Enable vertical sync: synchronizes software frame rate
# with your monitor's refresh rate.
vsync = true;

# Enable shadows.  Some modern GTK(4?) apps (Gimp, Nicotine, etc.) are
# impossible to use without shadows because the menus aren't visibly
# separated from the rest of the application.
shadow = true;
shadow-opacity = 1;
shadow-radius = 9;
shadow-offset-x = -9;
shadow-offset-y = -9;

# In the lines below, "class_i" and "class_g" refer to the instance and
# the general class of the window, respectively. This is the first and
# second value of _WM_CLASS (as reported by xprop).
shadow-exclude = [
    "class_g = 'systray'",
    "class_g = 'Google-chrome'",
    "class_g = 'firefox' && argb",
    "class_g = 'thunderbird-default' && argb",
    # Remove shadows inside windows, just below the i3 title bar.
    "class_g = 'i3-frame'",
    "class_g = 'Ferdium'",
    "class_g = 'Obsidian'",
    "class_g = 'Signal'",
    "class_g = 'steam'",
    "class_g = 'zoom'",
];

# Disable fading and blur.
fading = false;
blur-background = false;

# What do these options do?
use-ewmh-active-win = true;
unredir-if-possible = false;

wintypes:
{
    menu = { shadow = false; }
    tooltip = {shadow = false; }
    # Gets rid of shadows in docks, e.g., i3-bar.
    dock = { shadow = false; }
    splash = { shadow = false; }
};
