# NOTE: Editing this file (provided it's in ~/.config) will
# automatically restart picom.  No need to restart it.

# Perform all rendering operations with OpenGL.
backend = "glx";

# Enable vertical sync: synchronizes software frame rate
# with your monitor's refresh rate.
vsync = true;

# Enable shadows.  Some GTK(4?) apps (Gimp, Nicotine, etc.) are
# impossible to use without shadows because the menus aren't visibly
# separated from the rest of the application.
shadow = true;
shadow-opacity = 1;
shadow-radius = 9;
shadow-offset-x = -9;
shadow-offset-y = -9;
shadow-exclude = [
    "class_g = 'systray'",
    "class_g = 'Google-chrome'",
    "class_g = 'firefox' && argb",
    "class_g = 'thunderbird-default' && argb",
    # Remove shadows inside windows, just below the i3 title bar.
    "class_g = 'i3-frame'"
];

# Disable fading and blur.
fading = false;
blur-background = false;

# What do these options do?
use-ewmh-active-win = true;
unredir-if-possible = false;
